"""Turning a signal description into samples.

Decision record 0005 says signals are generated and never shipped, so a fixture
carries a description and this package is what makes it audible. The value of
that arrangement is entirely in the description being complete: a stimulus that
cannot be regenerated byte for byte from what the fixture says is a stimulus
nobody else has.

``docs/calibration.md`` is what this package is held to. It fixes what a level
means, what a full-scale sine wave is, how an amplitude maps to an integer
sample, and what the fade does to a level. Nothing here decides any of that; it
implements it, and where the two disagree the document is right.

The generator refuses rather than assumes. A description with no calibration
reference is the case the issue that built this names first, because a default
inside a generator is a convention nobody wrote down and it would move every
fixture at once.
"""

from eichstelle.signals.generator import (
    DEFAULT_PHASE,
    FADE_SHAPES,
    LEVEL_CONVENTIONS,
    DescriptionError,
    Modulated,
    Sinusoid,
    encode_pcm,
    parse_modulated,
    parse_sinusoid,
    render,
    render_modulated,
    write_wave,
)
from eichstelle.signals.noise import (
    BAND_LIMITED_NOISE,
    FILTER_ORDERS,
    FILTER_TYPES,
    NOISE,
    RANDOM_ALGORITHMS,
    SPECTRAL_SHAPES,
    Band,
    Biquad,
    Noise,
    gaussians,
    parse_noise,
    render_noise,
    words,
)

__all__ = [
    "BAND_LIMITED_NOISE",
    "DEFAULT_PHASE",
    "FADE_SHAPES",
    "FILTER_ORDERS",
    "FILTER_TYPES",
    "LEVEL_CONVENTIONS",
    "NOISE",
    "RANDOM_ALGORITHMS",
    "SPECTRAL_SHAPES",
    "Band",
    "Biquad",
    "DescriptionError",
    "Modulated",
    "Noise",
    "Sinusoid",
    "encode_pcm",
    "gaussians",
    "parse_modulated",
    "parse_noise",
    "parse_sinusoid",
    "render",
    "render_modulated",
    "render_noise",
    "words",
    "write_wave",
]
